### ISSUE TITLE
Doesn't work in Windows

### ISSUE THREAD

**Issue by MPV** [Maher4Ever/guard-phpunit#2]
Hi, 
It appears that this Guard plugin doesn't work in Windows. Do you think it would be possible to achieve?

When I try running it (with a guardfile that works fine in OS X), I get this:

```
ERROR: phpunit is not installed on your machine.
```

But PHPUnit is installed and I can run it with the "phpunit" command. 

Looking at the source code of this gem, it looks like it tries to use "which" to determine if phpunit is installed:

```
system('which phpunit > /dev/null 2>&1')
```

(See: https://github.com/Maher4Ever/guard-phpunit/blob/master/lib/guard/phpunit/runner.rb#L48)

To me it looks like it would work, if we change that code so it can use something else on Windows. What do you think?

**Checking for platform:**
This seems to be the best way of checking if you are running Ruby in Windows:

```
require 'rbconfig'
is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)
```

(See: http://stackoverflow.com/a/4871457)

**Checking if phpunit is installed:**
And "where" seems to be possible to use instead of "which" on Windows: 

```
> where phpunit
C:\utv\wamp\bin\php\php5.3.1\phpunit
C:\utv\wamp\bin\php\php5.3.1\phpunit.bat
```

(See: http://stackoverflow.com/a/304447)

**Using output from which (where):**
The only part I'm not sure about is the Windows equivalent of this: "`> /dev/null 2>&1`". Any ideas?

**Comment by Maher4Ever** [comment]
Sorry for taking forever to handle this. Thanks for the report and for the details you provided me with. It saved me the trouble of looking for it myself :).

I just pushed a fix for this issue and it works on my machine (Win 7 64-bit, WAMP with PEAR 1.9.4 and PHPUnit 3.6.11).

Could you try it out to make sure it works? I'll release a new version after you confirm.

**Comment by reflexator** [comment]
I have same issue, is fix released, I installed guard-phpunit through bundle

**Comment by Maher4Ever** [comment]
@reflexator I haven't released the fixed version yet because I need to confirm that it works first. Could you please add the following in your Gemfile:

``` ruby
gem 'guard-phpunit', :github => 'Maher4Ever/guard-phpunit'
```

Then run `bundle install`.

**Comment by brianium** [comment]
I have tested this on my machine. Win 7 64-bit using MINGW32.

`system(command)` 

on line 56 of runner.rb is always returning false despite PHPUnit being installed.

**Comment by brianium** [comment]
Is there an issue presented by using backticks? something like:

`!`phpunit --version`.empty?`

This would likely have to be put in a begin end clause, but it seems to make the tests pass.

**Comment by Maher4Ever** [comment]
@brianium What's the output of the following command on your machine? :

```
where phpunit
```

Also, are you sure that the `phpunit` command is in your command-prompt's `PATH`?

**Comment by brianium** [comment]
`where phpunit`

outputs:
c:\xampp\php\phpunit
c:\xampp\php\phpunit.bat

`echo $PATH` at the command line shows /c/xampp/php on my `PATH`

This would lead me to believe that the `system` call would return true, but it consistently returns false.

**Comment by Maher4Ever** [comment]
How did you install ruby on your machine? It seems to me that it's a ruby problem with the `system` command.

**Comment by brianium** [comment]
The only way I could get the relevant tests to pass was by updating runner.rb to the following:

``` ruby
def phpunit_exists?
    !exec_empty?
end

def exec_empty?
    output = ""
    begin
       output = `phpunit --version`
    end
    output.empty?
end
```

This obviously created issues with 2 tests verifying error output by stubbing the `system` call.

**Comment by brianium** [comment]
Ruby was installed using the RubyInstaller for Windows. http://rubyinstaller.org/

**Comment by Maher4Ever** [comment]
This is quite strange! I also use RubyInstaller for Windows. Your solution of checking whether the output is empty won't work though because windows would also print an error message when PHPUnit does not exist!

Does your system method ever return true? Try these two commands:

``` ruby
# Should return true
system 'exit 0'

# Should return false
system 'exit 1'
```

**Comment by brianium** [comment]
Running the above through irb I get the expected results.

The output solution throws an error if PHPUnit does not exist, so putting that in a `begin end` seems to leave output empty when PHPUnit does not exist.

This seems like a very strange issue. It's almost as if `system` is behaving differently under different contexts (irb vs the spec_runner)

**Comment by Maher4Ever** [comment]
I missed the fact that you were using the back-tick method and not `system`, so you are correct... it would work.
Using the back-tick method would also remove the need to change the command based on the operating system.

As for your problem with the `system` method, I would suggest re-installing RubyInstaller.

Thanks for the suggestion!

**Comment by brianium** [comment]
``` ruby
output = "";
begin
    output = `phpunit --version`
rescue
    output = ""
end
p output.empty?
```

seems to demonstrate the desired result. (not to repeat the above, just left out the rescue last time)

Thanks for the response! I'll give the re-install a try.

**Comment by brianium** [comment]
It appears the re-install did not address the issue. Very strange indeed.

**Comment by Maher4Ever** [comment]
@brianium Could you please try the new changes and confirm it works so I could release a new version of the gem? (It basically uses the same code you suggested ^^)

**Comment by brianium** [comment]
You got it.

**Comment by brianium** [comment]
`gem build guard-phpunit.gemspec`
`gem install guard-phpunit-0.1.3.gem`

ran `guard` against a project using PHPUnit,

and...

IT WORKS!

Thanks for getting this in there!

**Comment by brianium** [comment]
I should mention, that running `rake` against the test suite was giving some odd results when it came to the formatter receiving output, even after updating the git submodule. Good thing is, things are working.

**Comment by Maher4Ever** [comment]
@brianium Awesome! Thanks for testing the new changes :). I'll release a new version today.
