### ISSUE TITLE
Support guard 1.1.x

### ISSUE THREAD

**Issue by MPV** [Maher4Ever/guard-phpunit#3]
Hi, 
It appears that guard-phpunit requires "guard ~> 1.0.0":
https://github.com/Maher4Ever/guard-phpunit/blob/master/guard-phpunit.gemspec

This means that when we upgrade Guard to support other newer guards (like guard-livereload that requires "guard >= 1.1.0"), we cannot use guard-phpunit anymore. 

Does guard-phpunit support guard >= 1.1.0?

I could help testing guard-phpunit with Guard 1.1.x if you want but I'm not sure how to :(

**Comment by Maher4Ever** [comment]
Thanks for the report. I just released a new version to fix this.
