### ISSUE TITLE
Add support for specifying path to phpunit to avoid reliance on global install

### ISSUE THREAD

**Issue by gunnarlium** [Maher4Ever/guard-phpunit#5]
Now that phpunit has added support for installation via composer, it's easier to have local install per project, and thus avoid conflicts generated by global installs of phpunit.

If you could add an optional parameter for specyfing path to phpunit, I believe this would work great.

**Comment by MPV** [comment]
Can this be closed as a duplicate of https://github.com/Maher4Ever/guard-phpunit/pull/7?

**Comment by gunnarlium** [comment]
Yes.
